### PR TITLE
Unselect events: cache lookup key fix

### LINKED ISSUE #6128: Cannot unselect by clicking selected when using dataAdapter
When using select2 with `dataAdapter`, the selected option cannot be deselected by clicking it again on list.
If no `dataAdapter` option is used, it works fine, option can be deselected by clicking it second time.

Here's example with a bug I described, you can select any option and then try to deselect it by clicking it again.
http://jsfiddle.net/o53fLqum/

### PR DESCRIPTION
**Pull request by jayaddison**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- During `unselect` events, retrieve the HTML `option` element related to the unselection and use that as a cache key to retrieve item data

If this is related to an existing ticket, include a link to it as well.

Resolves #6128.

### CODE REVIEW

File: src/js/select2/data/select.js [hunk 1]
```diff
@@ -114,7 +114,12 @@ define([
     });
 
     container.on('unselect', function (params) {
-      self.unselect(params.data);
+      container.$element.find('option').each(function () {
+        if ($(this).val() == params.data.id) {
```
Comment (jayaddison) [inline src/js/select2/data/select.js:118]: Note: this is somewhat intentionally not a complete-strict equality test (in other words: it is expected that this is `==` instead of `===`)

This follows a similar equality pattern check in [`array.js` here](https://github.com/select2/select2/blob/5c38f186c98d793c7d396442986191ca05634d0a/src/js/select2/data/array.js#L47).

If both option-value and data-id are guaranteed to be of type `string`, then this could be upgraded to a strict equality test.

File: src/js/select2/data/select.js [hunk 2]
```diff
@@ -114,7 +114,12 @@ define([
     });
 
     container.on('unselect', function (params) {
-      self.unselect(params.data);
+      container.$element.find('option').each(function () {
```
Comment (jayaddison) [inline src/js/select2/data/select.js:117]: @kevin-brown I'm feeling a bit uncertain about whether this change is a good idea, after looking at it again.

This extra `for` loop feels like it could quite easily introduce performance regressions.

I'll find time to take another look at this soon, but if in any doubt, please feel free to revert this change.

Comment (jayaddison) [reply src/js/select2/data/select.js:117]: (update: re-inspecting this changeset currently)

Comment (jayaddison) [reply src/js/select2/data/select.js:117]: Yep, a slightly stronger statement after re-reading the changeset and related issues: I think I'd prefer for this pull request to be reverted (and #6128 re-opened), if that's OK.

I didn't add any test coverage as part of the changes, which was unwise, because that makes it much harder to determine whether the modifications truly resolve the issue identified in the linked ticket.

Comment (jayaddison) [reply src/js/select2/data/select.js:117]: (revert pull request opened as #6217)
